services:
    postgres:
        image: postgres:18
        volumes:
         - pgdata:/var/lib/postgresql/
        environment:
            POSTGRES_USER=postgres
            POSTGRES_PASSWORD=123
            POSTGRES_DB=apidata

    server:
        build: ./Server
        ports:
         - "5001:5001"

volumes:
    pgdata:
        external: true